STAR_TYPES = ['M', 'M', 'M', 'M', 'K', 'K', 'G', 'G', 'F']
HOT_STAR_TYPES = ['A', 'A','A', 'A', 'A', 'A', 'A', 'A', 'B', 'B', 'O']
SPECIAL_STAR_CLASSES = ['VI', 'VI', 'VI', 'VI', 'IV', 'IV', 'IV', 'III', 'III']
GIANT_STAR_CLASSES = ['III', 'III', 'III', 'III', 'III', 'III', 'III', 'II', 'II', 'Ib', 'Ia']
STAR_SUBTYPES = [0, 1, 3, 5, 7, 9, 8, 6, 2, 4, 0]
MSTAR_SUBTYPES = [8, 6, 5, 4, 0, 2, 1, 3, 5, 7, 9]
